'use strict';
/**
 * Minimal .xlsx reader - zero dependencies, Node built-ins only.
 *
 * WHY THIS EXISTS
 * ---------------
 * The spell roster arrives as a spreadsheet, and rebuilding the roster from it has to be
 * repeatable rather than a one-off. Every obvious way to read .xlsx pulls in a dependency,
 * and this project deliberately has none at runtime - `package.json` has no `dependencies`
 * block at all. Adding one just to read a file at build time would be the first crack in that.
 *
 * An .xlsx is a ZIP of XML. Node ships `zlib`, which is the only hard part, so the whole
 * reader is about 150 lines of central-directory walking and tag matching. It handles exactly
 * what this one spreadsheet needs and nothing more - no formulas, no styles, no dates.
 *
 *   const { readWorkbook } = require('./lib/xlsx');
 *   const wb = readWorkbook('roster.xlsx');
 *   wb.sheetNames                 -> ['spells', 'spell scaling']
 *   wb.sheet('spells')            -> [{ A: 'Lvl', C: 'Name', ... }, ...]  (row 1 = index 0)
 */

const fs = require('node:fs');
const zlib = require('node:zlib');

// ---------------------------------------------------------------- zip reading

const EOCD_SIG = 0x06054b50;
const CEN_SIG = 0x02014b50;

function readZip(filePath) {
  const buf = fs.readFileSync(filePath);

  // End-of-central-directory sits at the tail, after a comment of unknown length,
  // so scan backwards for its signature.
  let eocd = -1;
  for (let i = buf.length - 22; i >= 0 && i >= buf.length - 22 - 0xffff; i--) {
    if (buf.readUInt32LE(i) === EOCD_SIG) { eocd = i; break; }
  }
  if (eocd < 0) throw new Error(`not a zip file: ${filePath}`);

  const count = buf.readUInt16LE(eocd + 10);
  let p = buf.readUInt32LE(eocd + 16);

  const entries = new Map();
  for (let n = 0; n < count; n++) {
    if (buf.readUInt32LE(p) !== CEN_SIG) break;
    const method = buf.readUInt16LE(p + 10);
    const compSize = buf.readUInt32LE(p + 20);
    const nameLen = buf.readUInt16LE(p + 28);
    const extraLen = buf.readUInt16LE(p + 30);
    const commentLen = buf.readUInt16LE(p + 32);
    const localOff = buf.readUInt32LE(p + 42);
    const name = buf.toString('utf8', p + 46, p + 46 + nameLen);

    // The local header repeats the name/extra lengths, and they can differ from the
    // central directory's, so the data offset must be read from the local header.
    const lnLen = buf.readUInt16LE(localOff + 26);
    const leLen = buf.readUInt16LE(localOff + 28);
    const dataStart = localOff + 30 + lnLen + leLen;
    const raw = buf.subarray(dataStart, dataStart + compSize);

    entries.set(name, method === 0 ? raw : zlib.inflateRawSync(raw));
    p += 46 + nameLen + extraLen + commentLen;
  }
  return entries;
}

// ---------------------------------------------------------------- tiny XML helpers
//
// Deliberately regex-based rather than a parser. The XML here is machine-generated by Excel,
// flat, and never contains the constructs that make regex parsing a bad idea. Anything more
// would be a dependency or a lot more code for no gain on this one file.

function decodeEntities(s) {
  return s
    .replace(/&lt;/g, '<').replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"').replace(/&apos;/g, "'")
    .replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(Number(d)))
    .replace(/&#x([0-9a-fA-F]+);/g, (_, h) => String.fromCodePoint(parseInt(h, 16)))
    .replace(/&amp;/g, '&'); // last, so &amp;lt; survives as &lt;
}

/** All text inside a chunk, in document order - <si> cells split runs across many <t>. */
function innerText(chunk) {
  const out = [];
  const re = /<t\b[^>]*>([\s\S]*?)<\/t>/g;
  let m;
  while ((m = re.exec(chunk))) out.push(decodeEntities(m[1]));
  return out.join('');
}

function attr(tag, name) {
  const m = tag.match(new RegExp(`\\b${name}="([^"]*)"`));
  return m ? decodeEntities(m[1]) : null;
}

// ---------------------------------------------------------------- workbook

function readWorkbook(filePath) {
  const zip = readZip(filePath);
  const text = (n) => (zip.has(n) ? zip.get(n).toString('utf8') : null);

  // Shared string table. Excel stores most cell text here and cells reference it by index.
  const shared = [];
  const ss = text('xl/sharedStrings.xml');
  if (ss) {
    const re = /<si\b[^>]*>([\s\S]*?)<\/si>/g;
    let m;
    while ((m = re.exec(ss))) shared.push(innerText(m[1]));
  }

  // Sheet name -> part path, resolved through the workbook relationships.
  const rels = text('xl/_rels/workbook.xml.rels') || '';
  const relMap = new Map();
  for (const m of rels.matchAll(/<Relationship\b[^>]*\/?>/g)) {
    const id = attr(m[0], 'Id');
    let target = attr(m[0], 'Target') || '';
    if (target.startsWith('/')) target = target.slice(1);
    else if (!target.startsWith('xl/')) target = 'xl/' + target;
    if (id) relMap.set(id, target);
  }

  const wbXml = text('xl/workbook.xml') || '';
  const sheets = [];
  for (const m of wbXml.matchAll(/<sheet\b[^>]*\/?>/g)) {
    const name = attr(m[0], 'name');
    const rid = attr(m[0], 'r:id') || attr(m[0], 'id');
    const part = relMap.get(rid);
    if (name && part) sheets.push({ name, part });
  }

  function sheet(name) {
    const s = sheets.find((x) => x.name === name);
    if (!s) throw new Error(`no such sheet: ${name} (have: ${sheets.map((x) => x.name).join(', ')})`);
    const xml = text(s.part);
    if (xml == null) throw new Error(`sheet part missing: ${s.part}`);

    const rows = [];
    // NOTE the lazy quantifiers. An empty cell is written self-closing - <c r="D1" s="15"/> -
    // and with a greedy [^>]* the engine happily consumes the slash, falls through to the
    // ">...</c>" branch, and swallows the NEXT cell whole: column D silently takes column E's
    // value, unresolved. Same trap for self-closing <row/>. Lazy + an explicit self-closing
    // branch is the fix, and it is the reason this reader was cross-checked against a second
    // implementation before being trusted with the roster.
    for (const rm of xml.matchAll(/<row\b([^>]*?)(?:\/>|>([\s\S]*?)<\/row>)/g)) {
      const rowNum = Number(attr(`<row${rm[1]}>`, 'r') || 0);
      const cells = {};
      for (const cm of (rm[2] || '').matchAll(/<c\b([^>]*?)(?:\/>|>([\s\S]*?)<\/c>)/g)) {
        const head = `<c${cm[1]}>`;
        const ref = attr(head, 'r') || '';
        const col = ref.replace(/\d+/g, '');
        const type = attr(head, 't');
        const body = cm[2] || '';
        let value;
        if (type === 'inlineStr') {
          value = innerText(body);
        } else {
          const v = body.match(/<v\b[^>]*>([\s\S]*?)<\/v>/);
          if (!v) continue;
          const rawVal = decodeEntities(v[1]);
          value = type === 's' ? shared[Number(rawVal)] : rawVal;
        }
        if (value != null && value !== '') cells[col] = value;
      }
      if (Object.keys(cells).length) {
        rows[Math.max(0, rowNum - 1)] = cells;
      }
    }
    // Excel omits empty rows entirely; normalise the holes to {} so indexes stay meaningful.
    for (let i = 0; i < rows.length; i++) if (!rows[i]) rows[i] = {};
    return rows;
  }

  return { sheetNames: sheets.map((s) => s.name), sheet };
}

module.exports = { readWorkbook };
