const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('eqTracker', {
  getVersionInfo: () => ipcRenderer.invoke('app:getVersionInfo'),
  getChangelog: () => ipcRenderer.invoke('app:getChangelog'),

  getUiScale: () => ipcRenderer.invoke('ui:getScale'),
  setUiScale: (pct) => ipcRenderer.invoke('ui:setScale', pct),
  getSidebarWidth: () => ipcRenderer.invoke('ui:getSidebarWidth'),
  setSidebarWidth: (px) => ipcRenderer.invoke('ui:setSidebarWidth', px),
  getMergeRule: () => ipcRenderer.invoke('ui:getMergeRule'),
  setMergeRule: (rule) => ipcRenderer.invoke('ui:setMergeRule', rule),
  getSetupNudgeDismissed: () => ipcRenderer.invoke('ui:getSetupNudgeDismissed'),
  dismissSetupNudge: () => ipcRenderer.invoke('ui:dismissSetupNudge'),
  getSetupWizardDone: () => ipcRenderer.invoke('ui:getSetupWizardDone'),
  setSetupWizardDone: (done) => ipcRenderer.invoke('ui:setSetupWizardDone', done),
  getTradePing: () => ipcRenderer.invoke('ui:getTradePing'),
  setTradePing: (enabled) => ipcRenderer.invoke('ui:setTradePing', enabled),
  getTellPing: () => ipcRenderer.invoke('ui:getTellPing'),
  setTellPing: (enabled) => ipcRenderer.invoke('ui:setTellPing', enabled),
  getTellPingCooldownSec: () => ipcRenderer.invoke('ui:getTellPingCooldownSec'),
  setTellPingCooldownSec: (seconds) => ipcRenderer.invoke('ui:setTellPingCooldownSec', seconds),

  minimizeWindow: () => ipcRenderer.invoke('window:minimize'),
  toggleMaximizeWindow: () => ipcRenderer.invoke('window:maximizeToggle'),
  closeWindow: () => ipcRenderer.invoke('window:close'),
  isWindowMaximized: () => ipcRenderer.invoke('window:isMaximized'),
  onWindowMaximizedChange: (callback) => {
    ipcRenderer.on('window:maximized', () => callback(true));
    ipcRenderer.on('window:unmaximized', () => callback(false));
  },

  getLogState: () => ipcRenderer.invoke('log:getState'),
  chooseLogFolder: () => ipcRenderer.invoke('log:chooseFolder'),
  onLogStatus: (callback) => {
    ipcRenderer.on('log:status', (_event, status) => callback(status));
  },
  onLogLine: (callback) => {
    ipcRenderer.on('log:line', (_event, line) => callback(line));
  },
  onLogError: (callback) => {
    ipcRenderer.on('log:error', (_event, message) => callback(message));
  },
  onDebugLine: (callback) => {
    ipcRenderer.on('debug:line', (_event, line) => callback(line));
  },
  onMemorizedLine: (callback) => {
    ipcRenderer.on('memorized:line', (_event, line) => callback(line));
  },
  setSplitEnabled: (enabled) => ipcRenderer.invoke('log:setSplitEnabled', enabled),
  setSplitDayStartHour: (hour) => ipcRenderer.invoke('log:setSplitDayStartHour', hour),
  chooseSplitFolder: () => ipcRenderer.invoke('log:chooseSplitFolder'),
  resetSplitFolder: () => ipcRenderer.invoke('log:resetSplitFolder'),
  openLogFolder: () => ipcRenderer.invoke('log:openFolder'),
  archiveLogNow: () => ipcRenderer.invoke('log:archiveNow'),
  openArchiveFolder: () => ipcRenderer.invoke('log:openArchiveFolder'),
  launchArchiveCheck: () => ipcRenderer.invoke('log:launchArchiveCheck'),
  dismissArchivePrompt: () => ipcRenderer.invoke('log:dismissArchivePrompt'),

  getActiveBuffs: () => ipcRenderer.invoke('buffs:getActive'),
  getUnknownBuffs: () => ipcRenderer.invoke('buffs:getUnknown'),
  getKnownBuffs: () => ipcRenderer.invoke('buffs:getKnown'),
  resolveUnknownBuff: (name, durationSec, options = {}) =>
    ipcRenderer.invoke('buffs:resolveUnknown', { name, durationSec, ...options }),
  dismissUnknownBuff: (name) => ipcRenderer.invoke('buffs:dismissUnknown', name),
  removeActiveBuff: (name) => ipcRenderer.invoke('buffs:removeActive', name),
  getActiveAllyBuffs: () => ipcRenderer.invoke('buffs:getActiveAllies'),
  removeActiveAllyBuff: (allyName, name) => ipcRenderer.invoke('buffs:removeActiveAlly', { allyName, name }),
  onActiveAllyBuffsChanged: (callback) => {
    ipcRenderer.on('buffs:activeAllies', (_event, buffs) => callback(buffs));
  },

  getActiveCustomTimers: () => ipcRenderer.invoke('customTimers:getActive'),
  removeActiveCustomTimer: (id) => ipcRenderer.invoke('customTimers:removeActive', id),
  onActiveCustomTimersChanged: (callback) => {
    ipcRenderer.on('customTimers:active', (_event, timers) => callback(timers));
  },

  getActiveBardSongs: () => ipcRenderer.invoke('buffs:getActiveBardSongs'),
  removeActiveBardSong: (castBy, name) => ipcRenderer.invoke('buffs:removeActiveBardSong', { castBy, name }),
  onActiveBardSongsChanged: (callback) => {
    ipcRenderer.on('buffs:activeBardSongs', (_event, songs) => callback(songs));
  },
  getBlockedBuffs: () => ipcRenderer.invoke('buffs:getBlocked'),
  blockBuff: (name) => ipcRenderer.invoke('buffs:blockBuff', name),
  unblockBuff: (name) => ipcRenderer.invoke('buffs:unblockBuff', name),
  onBlockedBuffsChanged: (callback) => {
    ipcRenderer.on('buffs:blocked', (_event, blocked) => callback(blocked));
  },
  upsertKnownBuff: (name, durationSec, options = {}) =>
    ipcRenderer.invoke('buffs:upsertKnown', { name, durationSec, ...options }),
  removeKnownBuff: (name) => ipcRenderer.invoke('buffs:removeKnown', name),
  renameKnownBuff: (oldName, newName) => ipcRenderer.invoke('buffs:renameKnown', { oldName, newName }),
  onActiveBuffsChanged: (callback) => {
    ipcRenderer.on('buffs:active', (_event, buffs) => callback(buffs));
  },
  onUnknownBuffsChanged: (callback) => {
    ipcRenderer.on('buffs:unknown', (_event, buffs) => callback(buffs));
  },
  setShowOnOverlay: (name, showOnOverlay) =>
    ipcRenderer.invoke('buffs:setShowOnOverlay', { name, showOnOverlay }),
  setBardSong: (name, isBardSong) => ipcRenderer.invoke('buffs:setBardSong', { name, isBardSong }),
  setNoDurationScaling: (name, value) => ipcRenderer.invoke('buffs:setNoDurationScaling', { name, value }),

  getAmbiguousCasts: () => ipcRenderer.invoke('buffs:getAmbiguous'),
  resolveAmbiguousCast: (text, buffName) => ipcRenderer.invoke('buffs:resolveAmbiguous', { text, buffName }),
  dismissAmbiguousCast: (text) => ipcRenderer.invoke('buffs:dismissAmbiguous', text),
  resetAmbiguousResolutions: () => ipcRenderer.invoke('buffs:resetAmbiguousResolutions'),
  getAmbiguousResolutions: () => ipcRenderer.invoke('buffs:getAmbiguousResolutions'),
  removeAmbiguousResolution: (text, isSelf) => ipcRenderer.invoke('buffs:removeAmbiguousResolution', { text, isSelf }),
  onAmbiguousCastsChanged: (callback) => {
    ipcRenderer.on('buffs:ambiguous', (_event, casts) => callback(casts));
  },

  getTrackOthersEnabled: () => ipcRenderer.invoke('settings:getTrackOthers'),
  setTrackOthersEnabled: (enabled) => ipcRenderer.invoke('settings:setTrackOthers', enabled),
  getUseEvidenceModel: () => ipcRenderer.invoke('settings:getUseEvidenceModel'),
  setUseEvidenceModel: (enabled) => ipcRenderer.invoke('settings:setUseEvidenceModel', enabled),
  getUseCastTimeFilter: () => ipcRenderer.invoke('settings:getUseCastTimeFilter'),
  setUseCastTimeFilter: (enabled) => ipcRenderer.invoke('settings:setUseCastTimeFilter', enabled),
  getUseStackingModel: () => ipcRenderer.invoke('settings:getUseStackingModel'),
  setUseStackingModel: (enabled) => ipcRenderer.invoke('settings:setUseStackingModel', enabled),
  getAutoHideOverlayEnabled: () => ipcRenderer.invoke('settings:getAutoHideOverlay'),
  getShowAurasWhenAppFocused: () => ipcRenderer.invoke('settings:getShowAurasWhenAppFocused'),
  setShowAurasWhenAppFocused: (enabled) => ipcRenderer.invoke('settings:setShowAurasWhenAppFocused', enabled),
  getOverlayMasterState: () => ipcRenderer.invoke('overlay:getMasterState'),
  setOverlayAllUnlocked: (unlocked) => ipcRenderer.invoke('overlay:setAllUnlocked', unlocked),
  setOverlayMasterHidden: (hidden) => ipcRenderer.invoke('overlay:setMasterHidden', hidden),
  setOverlaySoundsMuted: (muted) => ipcRenderer.invoke('overlay:setSoundsMuted', muted),
  setOverlayPreviewAll: (enabled) => ipcRenderer.invoke('overlay:setPreviewAll', enabled),
  resumeMove: () => ipcRenderer.invoke('move:resume'),
  onOverlayMasterStateChanged: (callback) => {
    ipcRenderer.on('overlay:masterStateChanged', () => callback());
  },
  setAutoHideOverlayEnabled: (enabled) => ipcRenderer.invoke('settings:setAutoHideOverlay', enabled),

  getSpellbookState: () => ipcRenderer.invoke('spellbook:getState'),
  getSpellbookCharacter: () => ipcRenderer.invoke('spellbook:getCharacter'),
  setSpellbookCharacter: (name, server) => ipcRenderer.invoke('spellbook:setCharacter', { name, server }),
  listSpellbookCandidates: () => ipcRenderer.invoke('spellbook:listCandidates'),
  setSpellbookFileOverride: (filePath) => ipcRenderer.invoke('spellbook:setFileOverride', filePath),
  getMemorizedSpells: () => ipcRenderer.invoke('spellbook:getMemorized'),
  forgetMemorizedSpell: (name) => ipcRenderer.invoke('spellbook:forgetMemorized', name),
  clearMemorizedSpells: () => ipcRenderer.invoke('spellbook:clearMemorized'),
  onMemorizedSpellsChanged: (callback) => {
    ipcRenderer.on('spellbook:memorized', (_event, names) => callback(names));
  },

  getCharacterSettings: () => ipcRenderer.invoke('settings:getCharacter'),
  setCharacterSettings: (settings) => ipcRenderer.invoke('settings:setCharacter', settings),

  listWidgets: () => ipcRenderer.invoke('widget:list'),

  // Custom modules (feat/module-system).
  listModules: () => ipcRenderer.invoke('modules:list'),
  getModuleEntries: () => ipcRenderer.invoke('modules:entries'),
  getModuleSettings: (id) => ipcRenderer.invoke('modules:getSettings', id),
  setModuleSetting: (id, key, value) => ipcRenderer.invoke('modules:setSetting', { id, key, value }),
  setModuleEnabled: (id, enabled) => ipcRenderer.invoke('modules:setEnabled', { id, enabled }),
  onModuleError: (callback) => ipcRenderer.on('modules:error', (_event, e) => callback(e)),
  onModulesChanged: (callback) => ipcRenderer.on('modules:changed', (_event, list) => callback(list)),
  onModuleEntries: (callback) => ipcRenderer.on('modules:entries', (_event, all) => callback(all)),
  onModuleSettingsChanged: (callback) => ipcRenderer.on('modules:settingsChanged', (_event, p) => callback(p)),
  createWidget: (name, buffSource) => ipcRenderer.invoke('widget:create', { name, buffSource }),
  createAllyBuffsWidget: (name) => ipcRenderer.invoke('widget:createAlly', { name }),
  createBardSongsWidget: (name) => ipcRenderer.invoke('widget:createBardSongs', { name }),
  createRaidNamedWidget: (name) => ipcRenderer.invoke('widget:createRaidNamed', { name }),
  createModuleAuraWidget: (name, moduleId) => ipcRenderer.invoke('widget:createModuleAura', { name, moduleId }),
  createDebuffWidget: (name) => ipcRenderer.invoke('widget:createDebuff', { name }),
  createDamageMeterWidget: (name, mineOnly) => ipcRenderer.invoke('widget:createDamageMeter', { name, mineOnly }),
  createTravelGuideWidget: (name, destination) => ipcRenderer.invoke('widget:createTravelGuide', { name, destination }),
  createLockoutBoardWidget: (name) => ipcRenderer.invoke('widget:createLockoutBoard', { name }),
  createFirstAggroWidget: (name) => ipcRenderer.invoke('widget:createFirstAggro', { name }),
  setWidgetTravelDestination: (id, destination) => ipcRenderer.invoke('widget:setTravelDestination', { id, destination }),
  getTravelZones: () => ipcRenderer.invoke('travel:getZones'),
  // Raid lockouts. Read-only from the renderer's side: it asks for a projection and is told when
  // one changed. Nothing here can write state.
  getLogRotationStatus: () => ipcRenderer.invoke('logRotation:getStatus'),
  setLogRotationEnabled: (enabled) => ipcRenderer.invoke('logRotation:setEnabled', enabled),
  getLockouts: () => ipcRenderer.invoke('lockouts:get'),
  rescanLockouts: () => ipcRenderer.invoke('lockouts:rescan'),
  onLockoutsChanged: (cb) => { ipcRenderer.on('lockouts:changed', (_e, s) => cb(s)); },
  onLockoutBackfill: (cb) => { ipcRenderer.on('lockouts:backfill', (_e, s) => cb(s)); },
  // Lockouts-page log tools. The renderer shows in-app modals; these just move data.
  listLockoutLogFiles: () => ipcRenderer.invoke('lockouts:listLogFiles'),
  setLockoutLogTargetByPath: (p) => ipcRenderer.invoke('lockouts:setLogTargetByPath', p),
  addLockoutLogsByPaths: (paths) => ipcRenderer.invoke('lockouts:addLogsByPaths', paths),
  trimLockoutLog: () => ipcRenderer.invoke('lockouts:trim'),
  archiveHoldsCurrentWeek: () => ipcRenderer.invoke('log:archiveHoldsCurrentWeek'),
  // "EverQuest is running but not logging" - main watches for it, the renderer shows the modal.
  onLoggingOff: (cb) => { ipcRenderer.on('logging:off', () => cb()); },
  onLoggingOk: (cb) => { ipcRenderer.on('logging:ok', () => cb()); },
  acknowledgeLogging: () => ipcRenderer.invoke('logging:acknowledge'),
  recheckLogging: () => ipcRenderer.invoke('logging:recheck'),
  // The reset day/hour. One setting; the Lockouts page and the Setup page both edit it and both
  // hear when it changes.
  getLockoutReset: () => ipcRenderer.invoke('lockoutReset:get'),
  setLockoutReset: (rule) => ipcRenderer.invoke('lockoutReset:set', rule),
  onLockoutResetChanged: (cb) => { ipcRenderer.on('lockoutReset:changed', (_e, r) => cb(r)); },
  getTravelPickerCommand: () => ipcRenderer.invoke('travel:getPickerCommand'),
  setTravelPickerCommand: (word) => ipcRenderer.invoke('travel:setPickerCommand', word),
  // Note 30. Receive-only. There is no matching "apply this code from chat" channel on purpose -
  // the offer routes into the ordinary import screen, so nothing here can bypass its confirmations.
  onShareCodeOffered: (callback) => {
    ipcRenderer.on('shareCode:offered', (_event, offer) => callback(offer));
  },
  // Also receive-only: this LISTS codes seen in chat this session so a dismissed one can be found
  // again from "+ Add aura". Picking one fills the ordinary import box; it does not import.
  getRecentShareCodes: () => ipcRenderer.invoke('shareCode:recent'),
  createTextAuraWidget: (name, preset) => ipcRenderer.invoke('widget:createTextAura', { name, preset }),
  getCastableBuffs: () => ipcRenderer.invoke('buffs:castable'),
  getAllBuffNames: () => ipcRenderer.invoke('buffs:allNames'),
  createCooldownTimerWidget: (name, spellName, cooldownSec, iconId, buffDurationSec) =>
    ipcRenderer.invoke('widget:createCooldownTimer', { name, spellName, cooldownSec, iconId, buffDurationSec }),
  createBuffTimerWidget: (name, spellName, source) =>
    ipcRenderer.invoke('widget:createBuffTimer', { name, spellName, source }),
  getTrackableBuffs: () => ipcRenderer.invoke('buffs:trackable'),
  setWidgetTextAuraMessage: (id, value) => ipcRenderer.invoke('widget:setTextAuraMessage', { id, value }),
  setWidgetTextAuraSize: (id, value) => ipcRenderer.invoke('widget:setTextAuraSize', { id, value }),
  setWidgetTextAuraInstantSec: (id, value) =>
    ipcRenderer.invoke('widget:setTextAuraInstantSec', { id, value }),
  setWidgetStackTextLines: (id, value) => ipcRenderer.invoke('widget:setStackTextLines', { id, value }),
  setWidgetMaxStackTextLines: (id, value) =>
    ipcRenderer.invoke('widget:setMaxStackTextLines', { id, value }),
  setWidgetMergeSameDuration: (id, value) =>
    ipcRenderer.invoke('widget:setMergeSameDuration', { id, value }),
  setWidgetCategoryBorders: (id, value) => ipcRenderer.invoke('widget:setCategoryBorders', { id, value }),
  setWidgetCategoryBorderWidth: (id, px) => ipcRenderer.invoke('widget:setCategoryBorderWidth', { id, px }),
  setWidgetTrackOnEnemies: (id, value) => ipcRenderer.invoke('widget:setTrackOnEnemies', { id, value }),
  setWidgetDebuffCastBy: (id, value) => ipcRenderer.invoke('widget:setDebuffCastBy', { id, value }),
  setWidgetAllyDebuffAlert: (id, value) => ipcRenderer.invoke('widget:setAllyDebuffAlert', { id, value }),
  setWidgetDamageOptions: (id, options) => ipcRenderer.invoke('widget:setDamageOptions', { id, options }),
  setWidgetAlwaysOn: (id, value) => ipcRenderer.invoke('widget:setAlwaysOn', { id, value }),
  getHideHotkey: () => ipcRenderer.invoke('settings:getHideHotkey'),
  getHideHotkeyChoice: () => ipcRenderer.invoke('settings:getHideHotkeyChoice'),
  setHideHotkeyChoice: (choice) => ipcRenderer.invoke('settings:setHideHotkeyChoice', choice),
  getLoadoutLabel: () => ipcRenderer.invoke('settings:getLoadoutLabel'),
  onLoadoutLabelChanged: (cb) => ipcRenderer.on('settings:loadoutLabelChanged', (_e, v) => cb(v)),
  setLoadoutLabel: (enabled) => ipcRenderer.invoke('settings:setLoadoutLabel', enabled),
  openDebugLogFolder: () => ipcRenderer.invoke('debug:openLogFolder'),
  getDebugLogFolder: () => ipcRenderer.invoke('debug:logFolder'),
  getDebugLogEnabled: () => ipcRenderer.invoke('debug:getEnabled'),
  getRecentLogTail: (maxChars) => ipcRenderer.invoke('debug:getRecentLogTail', maxChars),
  setDebugLogEnabled: (enabled) => ipcRenderer.invoke('debug:setEnabled', enabled),
  getCurrentZone: () => ipcRenderer.invoke('zone:current'),
  getKnownZones: () => ipcRenderer.invoke('zone:known'),
  setWidgetVisibleInZones: (id, zones) => ipcRenderer.invoke('widget:setVisibleInZones', { id, zones }),
  onZoneChanged: (cb) => ipcRenderer.on('zone:changed', (_e, zone) => cb(zone)),
  setWidgetShowOnAllProfiles: (id, value) =>
    ipcRenderer.invoke('widget:setShowOnAllProfiles', { id, value }),
  // The nudge pad's centre button asked to open an aura's settings - see main.js.
  onOpenWidgetSettings: (callback) => {
    ipcRenderer.on('widget:openSettings', (_event, id) => callback(id));
  },
  exportWidget: (id) => ipcRenderer.invoke('widget:export', id),
  peekWidgetCode: (code) => ipcRenderer.invoke('widget:peekCode', code),
  importWidget: (code) => ipcRenderer.invoke('widget:import', code),
  duplicateWidget: (id) => ipcRenderer.invoke('widget:duplicate', id),
  applyCodeToSelfBuffs: (code) => ipcRenderer.invoke('widget:applyCodeToSelfBuffs', code),
  deleteWidget: (id) => ipcRenderer.invoke('widget:delete', id),
  reorderWidgets: (orderedIds) => ipcRenderer.invoke('widget:reorder', { orderedIds }),
  listAuraFolders: () => ipcRenderer.invoke('auraFolders:list'),
  createAuraFolder: (name) => ipcRenderer.invoke('auraFolders:create', name),
  renameAuraFolder: (id, name) => ipcRenderer.invoke('auraFolders:rename', { id, name }),
  deleteAuraFolder: (id) => ipcRenderer.invoke('auraFolders:delete', id),
  setAuraFolderCollapsed: (id, collapsed) => ipcRenderer.invoke('auraFolders:setCollapsed', { id, collapsed }),
  reorderAuraFolders: (orderedIds) => ipcRenderer.invoke('auraFolders:reorder', { orderedIds }),
  setWidgetFolder: (id, folderId) => ipcRenderer.invoke('widget:setFolder', { id, folderId }),
  resetWidgetToDefault: (id) => ipcRenderer.invoke('widget:resetToDefault', { id }),
  setWidgetName: (id, name) => ipcRenderer.invoke('widget:setName', { id, value: name }),
  toggleWidgetLock: (id) => ipcRenderer.invoke('widget:toggleLock', id),
  resetWidgetPosition: (id) => ipcRenderer.invoke('widget:resetPosition', id),
  isWidgetLocked: (id) => ipcRenderer.invoke('widget:isLocked', id),
  enterWidgetMoveMode: (id) => ipcRenderer.invoke('widget:enterMoveMode', id),
  setWidgetDisplayMode: (id, mode) => ipcRenderer.invoke('widget:setDisplayMode', { id, mode }),
  setWidgetTimerFormat: (id, format) => ipcRenderer.invoke('widget:setTimerFormat', { id, value: format }),
  setWidgetTextSize: (id, size) => ipcRenderer.invoke('widget:setTextSize', { id, value: size }),
  setWidgetIconSize: (id, size) => ipcRenderer.invoke('widget:setIconSize', { id, value: size }),
  setWidgetContentAnchor: (id, anchor) => ipcRenderer.invoke('widget:setContentAnchor', { id, value: anchor }),
  setWidgetIconsPerRow: (id, count) => ipcRenderer.invoke('widget:setIconsPerRow', { id, value: count }),
  setWidgetRowSize: (id, size) => ipcRenderer.invoke('widget:setRowSize', { id, value: size }),
  setWidgetSortOrder: (id, order) => ipcRenderer.invoke('widget:setSortOrder', { id, value: order }),
  setWidgetLowTimeThreshold: (id, seconds) => ipcRenderer.invoke('widget:setLowTimeThreshold', { id, value: seconds }),
  setWidgetLandingGlowEnabled: (id, enabled) => ipcRenderer.invoke('widget:setLandingGlowEnabled', { id, enabled }),
  setWidgetHideBardSongs: (id, hide) => ipcRenderer.invoke('widget:setHideBardSongs', { id, hide }),
  setWidgetShowRowIcon: (id, enabled) => ipcRenderer.invoke('widget:setShowRowIcon', { id, enabled }),
  setWidgetMirrorRowDirection: (id, enabled) => ipcRenderer.invoke('widget:setMirrorRowDirection', { id, enabled }),
  setWidgetShowIconLabel: (id, enabled) => ipcRenderer.invoke('widget:setShowIconLabel', { id, enabled }),
  setWidgetIconDepletionShade: (id, value) => ipcRenderer.invoke('widget:setIconDepletionShade', { id, value }),
  setWidgetTimerColorRamp: (id, enabled) => ipcRenderer.invoke('widget:setTimerColorRamp', { id, enabled }),
  setWidgetExpiredLingerSec: (id, seconds) => ipcRenderer.invoke('widget:setExpiredLingerSec', { id, seconds }),
  setWidgetIconLabelSize: (id, size) => ipcRenderer.invoke('widget:setIconLabelSize', { id, value: size }),
  setWidgetIconLabelAnchor: (id, anchor) => ipcRenderer.invoke('widget:setIconLabelAnchor', { id, value: anchor }),
  setWidgetTimerTextColor: (id, value) => ipcRenderer.invoke('widget:setTimerTextColor', { id, value }),
  setWidgetGroupAllyBuffs: (id, value) => ipcRenderer.invoke('widget:setGroupAllyBuffs', { id, value }),
  setWidgetShowDebuffSongs: (id, value) => ipcRenderer.invoke('widget:setShowDebuffSongs', { id, value }),
  setWidgetSplitSongsByType: (id, value) => ipcRenderer.invoke('widget:setSplitSongsByType', { id, value }),
  setWidgetGroupAllyDirection: (id, value) => ipcRenderer.invoke('widget:setGroupAllyDirection', { id, value }),
  setWidgetHideAllyNameOnTile: (id, value) => ipcRenderer.invoke('widget:setHideAllyNameOnTile', { id, value }),
  setWidgetLabelTextColor: (id, value) => ipcRenderer.invoke('widget:setLabelTextColor', { id, value }),
  setWidgetIconMargin: (id, value) => ipcRenderer.invoke('widget:setIconMargin', { id, value }),
  setWidgetWrapText: (id, enabled) => ipcRenderer.invoke('widget:setWrapText', { id, enabled }),
  setWidgetIconJustify: (id, value) => ipcRenderer.invoke('widget:setIconJustify', { id, value }),
  setWidgetTextJustify: (id, value) => ipcRenderer.invoke('widget:setTextJustify', { id, value }),
  setWidgetMaxDurationFilter: (id, seconds) => ipcRenderer.invoke('widget:setMaxDurationFilter', { id, value: seconds }),
  setWidgetSoundOnLand: (id, enabled) => ipcRenderer.invoke('widget:setSoundOnLand', { id, enabled }),
  setWidgetSoundOnExpire: (id, enabled) => ipcRenderer.invoke('widget:setSoundOnExpire', { id, enabled }),
  setWidgetSoundWarningSec: (id, seconds) => ipcRenderer.invoke('widget:setSoundWarningSec', { id, value: seconds }),
  setWidgetSoundWarningLoopSec: (id, seconds) => ipcRenderer.invoke('widget:setSoundWarningLoopSec', { id, value: seconds }),
  setWidgetSoundCooldownSec: (id, seconds) => ipcRenderer.invoke('widget:setSoundCooldownSec', { id, value: seconds }),
  setWidgetLandSoundId: (id, soundId) => ipcRenderer.invoke('widget:setLandSoundId', { id, soundId }),
  setWidgetExpireSoundId: (id, soundId) => ipcRenderer.invoke('widget:setExpireSoundId', { id, soundId }),
  setWidgetWarningSoundId: (id, soundId) => ipcRenderer.invoke('widget:setWarningSoundId', { id, soundId }),
  setWidgetAlertVolume: (id, volume) => ipcRenderer.invoke('widget:setAlertVolume', { id, value: volume }),
  pickSound: () => ipcRenderer.invoke('sounds:pick'),
  getSoundInfo: (id) => ipcRenderer.invoke('sounds:getInfo', id),
  openSoundsFolder: () => ipcRenderer.invoke('sounds:openFolder'),
  openConfigFolder: () => ipcRenderer.invoke('app:openConfigFolder'),
  openExternal: (url) => ipcRenderer.invoke('app:openExternal', url),
  backupConfig: () => ipcRenderer.invoke('app:backupConfig'),
  exportConfig: () => ipcRenderer.invoke('config:export'),
  listImportableConfig: () => ipcRenderer.invoke('config:listImportable'),
  importConfig: (sourcePath) => ipcRenderer.invoke('config:import', sourcePath),
  openExportsFolder: () => ipcRenderer.invoke('config:openExportsFolder'),
  getLogActivity: () => ipcRenderer.invoke('log:activity'),
  getFullscreenState: () => ipcRenderer.invoke('overlay:fullscreenState'),
  onFullscreenWarning: (cb) => ipcRenderer.on('overlay:fullscreenWarning', (_e, active) => cb(active)),
  getAutoHideAvailable: () => ipcRenderer.invoke('overlay:autoHideAvailable'),
  onAutoHideUnavailable: (cb) => ipcRenderer.on('overlay:autoHideUnavailable', () => cb()),
  previewWidget: (id) => ipcRenderer.invoke('widget:preview', id),
  isWidgetPreviewing: (id) => ipcRenderer.invoke('widget:isPreviewing', id),
  setWidgetListWidth: (id, width) => ipcRenderer.invoke('widget:setListWidth', { id, value: width }),
  setWidgetLockoutOptions: (id, opts) => ipcRenderer.invoke('widget:setLockoutOptions', { id, ...opts }),
  setWidgetOpacity: (id, opacity) => ipcRenderer.invoke('widget:setOpacity', { id, value: opacity }),
  setWidgetBuffFilter: (id, mode, names) => ipcRenderer.invoke('widget:setBuffFilter', { id, mode, names }),
  setWidgetBuffSource: (id, source) => ipcRenderer.invoke('widget:setBuffSource', { id, source }),
  addWidgetCustomTimer: (id, timer) => ipcRenderer.invoke('widget:addCustomTimer', { id, ...timer }),
  setWidgetTriggerDurationSec: (id, seconds) => ipcRenderer.invoke('widget:setTriggerDurationSec', { id, seconds }),
  setWidgetTriggerCombineMode: (id, mode) => ipcRenderer.invoke('widget:setTriggerCombineMode', { id, mode }),
  setWidgetAndWindowSec: (id, seconds) => ipcRenderer.invoke('widget:setAndWindowSec', { id, seconds }),
  setWidgetReverseDetection: (id, enabled) => ipcRenderer.invoke('widget:setReverseDetection', { id, enabled }),
  updateWidgetCustomTimer: (id, timerId, timer) =>
    ipcRenderer.invoke('widget:updateCustomTimer', { id, timerId, ...timer }),
  removeWidgetCustomTimer: (id, timerId) => ipcRenderer.invoke('widget:removeCustomTimer', { id, timerId }),
  excludeWidgetBuff: (id, name) => ipcRenderer.invoke('widget:excludeBuff', { id, name }),
  unexcludeWidgetBuff: (id, name) => ipcRenderer.invoke('widget:unexcludeBuff', { id, name }),
  setWidgetActiveProfileIds: (id, profileIds) => ipcRenderer.invoke('widget:setActiveProfileIds', { id, profileIds }),

  getProfiles: () => ipcRenderer.invoke('profiles:list'),
  getActiveProfileId: () => ipcRenderer.invoke('profiles:getActiveId'),
  createProfile: (name, widgetIdsToMigrate) => ipcRenderer.invoke('profiles:create', { name, widgetIdsToMigrate }),
  renameProfile: (id, name) => ipcRenderer.invoke('profiles:rename', { id, name }),
  setActiveProfile: (id) => ipcRenderer.invoke('profiles:setActive', id),
  deleteProfile: (id) => ipcRenderer.invoke('profiles:delete', id),
  onProfilesChanged: (callback) => {
    ipcRenderer.on('profiles:changed', (_event, profiles) => callback(profiles));
  },
  onActiveProfileChanged: (callback) => {
    ipcRenderer.on('profiles:activeChanged', (_event, id) => callback(id));
  },

  // The buff optimiser (buffPlanner.js). Input lives on the active loadout profile; the plan is
  // always recomputed on the main side from the live roster.
  getPlannerInput: (profileId) => ipcRenderer.invoke('planner:getInput', profileId),
  setPlannerClasses: (profileId, classes) => ipcRenderer.invoke('planner:setClasses', { profileId, classes }),
  setPlannerLevel: (profileId, level) => ipcRenderer.invoke('planner:setLevel', { profileId, level }),
  setPlannerOrder: (profileId, order) => ipcRenderer.invoke('planner:setOrder', { profileId, order }),
  setPlannerPlaystyle: (profileId, playstyle) => ipcRenderer.invoke('planner:setPlaystyle', { profileId, playstyle }),
  computePlan: (profileId) => ipcRenderer.invoke('planner:compute', profileId),

  getIconSets: () => ipcRenderer.invoke('icons:getSets'),
  getIconSet: () => ipcRenderer.invoke('icons:getSet'),
  setIconSet: (iconSet) => ipcRenderer.invoke('icons:setSet', iconSet),
  getIconCount: () => ipcRenderer.invoke('icons:getCount'),

  listActionBars: () => ipcRenderer.invoke('actionBar:list'),
  createActionBar: (name) => ipcRenderer.invoke('actionBar:create', { name }),
  deleteActionBar: (id) => ipcRenderer.invoke('actionBar:delete', id),
  setActionBarName: (id, name) => ipcRenderer.invoke('actionBar:setName', { id, name }),
  getActionBarConfig: (id) => ipcRenderer.invoke('actionBar:getConfig', id),
  setActionBarIconsPerRow: (id, count) => ipcRenderer.invoke('actionBar:setIconsPerRow', { id, count }),
  setActionBarIconSize: (id, px) => ipcRenderer.invoke('actionBar:setIconSize', { id, px }),
  setActionBarMarginPx: (id, px) => ipcRenderer.invoke('actionBar:setMarginPx', { id, px }),
  setActionBarVisible: (id, visible) => ipcRenderer.invoke('actionBar:setVisible', { id, visible }),
  setActionBarShowWhenAppFocused: (id, enabled) => ipcRenderer.invoke('actionBar:setShowWhenAppFocused', { id, enabled }),
  toggleActionBarLock: (id) => ipcRenderer.invoke('actionBar:toggleLock', id),
  isActionBarLocked: (id) => ipcRenderer.invoke('actionBar:isLocked', id),
  resetActionBarPosition: (id) => ipcRenderer.invoke('actionBar:resetPosition', id),
  swapActionBarSlots: (id, a, b) => ipcRenderer.invoke('actionBar:swapSlots', { id, a, b }),
  enterActionBarMoveMode: (id) => ipcRenderer.invoke('actionBar:enterMoveMode', id),
  setActionBarSlotIcon: (id, index, iconId) => ipcRenderer.invoke('actionBar:setSlotIcon', { id, index, iconId }),
  setActionBarOpacity: (id, opacity) => ipcRenderer.invoke('actionBar:setOpacity', { id, opacity }),
  setActionBarSlotName: (id, index, name) => ipcRenderer.invoke('actionBar:setSlotName', { id, index, name }),
  setActionBarSlotDisabled: (id, index, disabled) => ipcRenderer.invoke('actionBar:setSlotDisabled', { id, index, disabled }),
  setActionBarSlotCooldown: (id, index, cooldown) => ipcRenderer.invoke('actionBar:setSlotCooldown', { id, index, cooldown }),
  setActionBarSlotCount: (id, count) => ipcRenderer.invoke('actionBar:setSlotCount', { id, count }),
  setActionBarCooldownStyle: (id, style) => ipcRenderer.invoke('actionBar:setCooldownStyle', { id, style }),
  setActionBarCooldownShowNumber: (id, enabled) => ipcRenderer.invoke('actionBar:setCooldownShowNumber', { id, enabled }),
  setActionBarNameLabelSize: (id, size) => ipcRenderer.invoke('actionBar:setNameLabelSize', { id, size }),
  setActionBarNameLabelAnchor: (id, anchor) => ipcRenderer.invoke('actionBar:setNameLabelAnchor', { id, anchor }),
  setActionBarNameLabelColor: (id, color) => ipcRenderer.invoke('actionBar:setNameLabelColor', { id, color }),
  setActionBarNameLabelWrap: (id, wrap) => ipcRenderer.invoke('actionBar:setNameLabelWrap', { id, wrap }),
  setActionBarCooldownTextSize: (id, size) => ipcRenderer.invoke('actionBar:setCooldownTextSize', { id, size }),
  setActionBarCooldownTextAnchor: (id, anchor) => ipcRenderer.invoke('actionBar:setCooldownTextAnchor', { id, anchor }),
  setActionBarCooldownTextColor: (id, color) => ipcRenderer.invoke('actionBar:setCooldownTextColor', { id, color }),
  setActionBarCooldownTextWrap: (id, wrap) => ipcRenderer.invoke('actionBar:setCooldownTextWrap', { id, wrap }),
  setActionBarCooldownReplacesLabel: (id, replaces) => ipcRenderer.invoke('actionBar:setCooldownReplacesLabel', { id, replaces }),
  setActionBarBorderWidth: (id, px) => ipcRenderer.invoke('actionBar:setBorderWidth', { id, px }),
  setActionBarBorderOffset: (id, px) => ipcRenderer.invoke('actionBar:setBorderOffset', { id, px }),
  setActionBarBorderColor: (id, color) => ipcRenderer.invoke('actionBar:setBorderColor', { id, color }),
  setActionBarSlotBgColor: (id, index, color) => ipcRenderer.invoke('actionBar:setSlotBgColor', { id, index, color }),
  setActionBarSlotNameSizeOverride: (id, index, size) => ipcRenderer.invoke('actionBar:setSlotNameSizeOverride', { id, index, size }),
  setActionBarSlotInsetPx: (id, index, px) => ipcRenderer.invoke('actionBar:setSlotInsetPx', { id, index, px }),
  setActionBarSlotToggleGroup: (id, index, group) => ipcRenderer.invoke('actionBar:setSlotToggleGroup', { id, index, group }),
  setActionBarSlotToggleName: (id, index, name) => ipcRenderer.invoke('actionBar:setSlotToggleName', { id, index, name }),
  setActionBarSlotToggleDurationSec: (id, index, sec) => ipcRenderer.invoke('actionBar:setSlotToggleDurationSec', { id, index, sec }),
  getKnownAbilityGroups: () => ipcRenderer.invoke('actionBar:getKnownAbilityGroups'),
  setActionBarSlotMultiIcon: (id, index, enabled) => ipcRenderer.invoke('actionBar:setSlotMultiIcon', { id, index, enabled }),
  setActionBarSlotSecondIcon: (id, index, iconId) => ipcRenderer.invoke('actionBar:setSlotSecondIcon', { id, index, iconId }),
  setActionBarSlotBorderEnabled: (id, index, enabled) => ipcRenderer.invoke('actionBar:setSlotBorderEnabled', { id, index, enabled }),
  setActionBarSlotBorderWidth: (id, index, px) => ipcRenderer.invoke('actionBar:setSlotBorderWidth', { id, index, px }),
  setActionBarSlotBorderOffset: (id, index, px) => ipcRenderer.invoke('actionBar:setSlotBorderOffset', { id, index, px }),
  setActionBarSlotBorderColor: (id, index, color) => ipcRenderer.invoke('actionBar:setSlotBorderColor', { id, index, color }),
  setActionBarActiveProfileIds: (id, profileIds) => ipcRenderer.invoke('actionBar:setActiveProfileIds', { id, profileIds }),
  copyActionBarSettings: (id, fromId) => ipcRenderer.invoke('actionBar:copySettings', { id, fromId }),
  duplicateActionBar: (id) => ipcRenderer.invoke('actionBar:duplicate', id),
  clearAllActionBarTextOverrides: (id) => ipcRenderer.invoke('actionBar:clearAllTextOverrides', id),
});
